name: hotkey_system
description: This plugin allows Flutter desktop apps to defines system/inapp wide hotkey (i.e. shortcut).
version: 0.0.2
repository: https://github.com/suysoftware/hotkey_system


platforms:
  macos:

screenshots:
  - description: Hotkey System Logo.
    path: assets/hs_logo_192.png

topics:
  - hotkey
  - shortcuts
  - keyboard
  - macos-shortcuts
  - hardware-keyboard

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  uuid: ^3.0.7

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: HotkeySystemPlugin
